### ISSUE TITLE
conekta_object.inspect is missing data

### ISSUE THREAD

**Issue by grillermo** [conekta/conekta-ruby#11]
It seems that @values.inspect is not exhaustive. 
If you do 
customer.inspect 

    "{\"id\"=>\"cus_zNtuDyNVWAu6FqoKu\", \"email\"=>\"my.mail@gmail.com\", \"name\"=>\"Juan\", \"phone\"=>\"12345\", \"livemode\"=>false, \"default_card_id\"=>\"card_G3sdsddsds\", \"object\"=>\"customer\", \"created_at\"=>1423507954, \"cards\"=>[{\"id\"=>\"card_G3sdsddsds\", \"created_at\"=>1423507954, \"active\"=>true, \"last4\"=>\"4242\", \"object\"=>\"card\", \"exp_month\"=>\"12\", \"exp_year\"=>\"19\", \"brand\"=>\"VISA\", \"name\"=>\"Jorge Lopez\", \"customer_id\"=>\"cus_zNtuDyNVWAu6FqoKu\"}], \"subscription\"=>nil}"

As shown by the docs. Please notice the last part, it has the card information.
But if you do
customer.values

    {"id"=>"cus_zNtuDyNVWAu6FqoKu",
    "email"=>"guillermo.siliceo@gmail.com",
    "name"=>"Juan",
    "phone"=>"12345",
    "livemode"=>false,
    "default_card_id"=>"card_G3jFzdh2rSupP2Do",
    "object"=>"customer",
    "created_at"=>1423507954,
    "cards"=>{0=>{}},
    "subscription"=>nil}

The cards information is missing, and looking at the implementation

    https://github.com/conekta/conekta-ruby/blob/afce2f479ed1ccec74fe3e6e8c0a2a3a046c8e88/lib/conekta/conekta_object.rb#L34

It seems that 

     @values.inspect 

Is the culprit. 

This 'bug' forces me to do

eval customer.inspect

To access the card info, which is nasty.

**Comment by grillermo** [comment]
Oddly enough, doing 

    puts customer.inspect

Does show the object as in the docs,

**Comment by MauricioMurga** [comment]
@grillermo, I'm trying to replicate this error but in my console I get the following output with the card information:

customer.values
 => {"id"=>"cus_XSwRTmCVQNdBZ4BMQ", "email"=>nil, "name"=>nil, "phone"=>nil, "livemode"=>false, "default_card_id"=>"card_rd2TmDb7hERtLXRK", "object"=>"customer", "created_at"=>1423850545, "cards"=>[{"id"=>"card_rd2TmDb7hERtLXRK", "created_at"=>1423850545, "active"=>true, "last4"=>"4242", "object"=>"card", "exp_month"=>"12", "exp_year"=>"19", "brand"=>"VISA", "name"=>"Jorge Lopez", "customer_id"=>"cus_XSwRTmCVQNdBZ4BMQ"}], "subscription"=>nil}

I'm using Conekta 0.5.1 and I got the customer using create and find. Please provide the complete code block so I can replicate this error and fix it as soon as possible.

Thanks

**Comment by MauricioMurga** [comment]
@grillermo, I'm closing this issue but I can re-open it if you can provide more information about it.
