### ISSUE TITLE
Rspec no debería de ser un runtime dependency

### ISSUE THREAD

**Issue by maca** [conekta/conekta-ruby#12]
Rspec debería de ser un development_dependency, de ese modo no tengo que actualizar conekta cuando quiero una versión más reciente de rspec.

https://github.com/conekta/conekta-ruby/blob/master/conekta.gemspec#23

**Comment by MauricioMurga** [comment]
@maca, gracias por el comentario. Hice el cambio en la nueva versión: https://github.com/conekta/conekta-ruby/releases/tag/v0.5.2
