### ISSUE TITLE
update plan spec failing

### ISSUE THREAD

**Issue by acolin** [conekta/conekta-ruby#14]
Seems like the api is not accepting a patch update, also expects the amount to be present.
![screen shot 2015-04-20 at 10 41 04 pm](https://cloud.githubusercontent.com/assets/698536/7245307/6cbcc378-e7ae-11e4-814f-c4f63417c24a.png)

**Comment by MauricioMurga** [comment]
Thanks for noticing @acolin, we'll check on the API end the changes that have to be done to fix this bug tomorrow.

**Comment by MauricioMurga** [comment]
I already updated the update logic for plan. You can only update amount or name and none are mandatory for the update. Let me know if you have any doubts.
