### ISSUE TITLE
Empty hash when I try to assign a ConektaCard 

### ISSUE THREAD

**Issue by Kentverger** [conekta/conekta-ruby#21]
When I execute `user.cards`, obviously users is an instances of Customer class, it returns:
`{0=>{}}`

When I execute for instance:
`user.cards.each do |card| puts card[1] end`
It prints 
`{"id"=>"card_snbfM58GGte58NWr", "created_at"=>1441068616, "active"=>true, "last4"=>"4242", "object"=>"card", "exp_month"=>"03", "exp_year"=>"19", "brand"=>"VISA", "name"=>"Pedro", "customer_id"=>"cus_im7DqkALerT7isuDR"}
`

then I try to assign or convert the hash to an array I get empty hash

    cards_array = []
    user.cards.each do |card| cards_array << card[1] end
    cards_array
I get an empty hash for every card.
`[{}]`
This  behaviour is intencional or is a bug?

**Comment by MauricioMurga** [comment]
Hi @Kentverger,
[Conekta objects](https://github.com/conekta/conekta-ruby/blob/master/lib/conekta/conekta_object.rb) are not meant to be changed directly. Conekta objects have a Hash called "values" that stores objects such as cards for customers and it's read-only. However, it should not print an empty hash when accessed ({0=>{}}).
May I ask which version of this library are you using as well of your current ruby version? I could not replicate this behaviour.

Thanks,

**Comment by Kentverger** [comment]
Hi, thanks for the answer I am using 0.4.3 version
`gem 'conekta', '0.4.3'`

**Comment by MauricioMurga** [comment]
Hi @Kentverger, you should probably update to a later version. I believe this issue was fixed in 0.4.4 and later. However, you should update to the latest version if possible.

I will close this issue but let me know if the update was not enough.

Thanks

**Comment by Kentverger** [comment]
Mejor en español XD me resulta mas comodo. 

Actualice la gema pero sigue el problema.

**Comment by MauricioMurga** [comment]
Hola @Kentverger, me puedes decir a qué versión lo actualizaste y qué versión de ruby usas? Me gustaría poder replicar el error.

**Comment by Kentverger** [comment]
Claro, mira asi esta mi gemfile

    ruby '2.0.0'
    gem 'rails', '4.0.5' 
    gem 'conekta', '0.5.3'

**Comment by MauricioMurga** [comment]
Hola @Kentverger, he reparado este bug en el siguiente [https://github.com/conekta/conekta-ruby/pull/22](PR). Ya está hecho el merge para la nueva versión que es la 0.5.4. Muchas gracias por tu ayuda!
