### ISSUE TITLE
Forma de especificar tipos de producto

### ISSUE THREAD

**Issue by bntzio** [conekta/conekta-ruby#26]
A la hora de generar un cargo, ejemplo:

```ruby
  def charge
    begin
      @charge = Conekta::Charge.create({
        amount: params['chargeInCents'],
        currency: "MXN",
        description: "Pizza Delivery at test",
        reference_id: "001-id-test",
        details:
        {
          email: params['emailBuyer'],
          line_items: [
            { name: 'Pizza at test',
              description: 'A pizza test description',
              unit_price: params['chargeInCents'],
              quantity: 1,
              sku: 'pizza-test',
              type: 'pizza'
            }
          ]
        },
        card: params['conektaTokenId']
      })
    rescue Conekta::ParameterValidationError => e
      puts e.message_to_purchaser
      #alguno de los parámetros fueron inválidos
    rescue Conekta::ProcessingError => e
      puts e.message_to_purchaser
      #la tarjeta no pudo ser procesada
    rescue Conekta::Error
      puts e.message_to_purchaser
      #un error ocurrió que no sucede en el flujo normal de cobros como por ejemplo un auth_key incorrecto
    end
  end
```

Tal y cómo esta especificado en la [API de Conekta](https://www.conekta.io/es/docs/api?language=ruby&vertical=productos-digitales#cargos) y en [éste](https://github.com/conekta-examples/hello-conekta-ruby-rails/blob/master/app/controllers/checkouts_controller.rb) ejemplo.

El cargo es `nil` y no se crea.

En los mensajes (rescue) de Conekta, tira los siguientes errores en la consola:
```bash
  El campo de shipment es obligatorio para productos físicos.
``` 

Como si se estuviera generando un cargo de un producto físico por defecto.

¿Habrá manera de especificar en el objecto `charge` el tipo de producto a crear (productos físicos o digitales) de tal manera que ignore los parámetros cómo **shipment** para productos digitales?

**Comment by Janee** [comment]
Hola! @bntzio los parámetros requeridos (digitales o físicos) dependen de como te registraste con nosotros, no es posible omitirlos.

**Comment by bntzio** [comment]
@Janee Oh ok! No lo recordaba, hace años que cree la cuenta jeje, muchas gracias! :smile:
