### ISSUE TITLE
Método de pago vacío.

### ISSUE THREAD

**Issue by julio336** [conekta/conekta-ruby#27]
Estoy siguiendo el tutorial que tienen en RUBY y solamente obtengo el error: "Método de pago vacío."

Después de declarar mi variable de instancia @charge, aparece el error de 'nil' para los valores @charge.amount y @charge.status. ¿que estoy haciendo mal?

Saludos.

**Comment by leofischer** [comment]
@Janee, podrias apoyar en checar que esta mal?

**Comment by Janee** [comment]
Hola @julio336 ¿tendrás el link del repo o podrás pasar la parte del código? Te invito a que revises nuestro [repo](https://github.com/conekta-examples/hello-conekta-ruby-rails) ejemplo.

**Comment by julio336** [comment]
Aqui les dejo un link con mi app:
https://github.com/julio336/realdellago

Saludos.

**Comment by Janee** [comment]
@julio336 te envié un pull request con el fix, era error de instalación :)

**Comment by julio336** [comment]
Nuevamente tengo problemas, me sale el siguiente error:

Parameters: {"utf8"=>"✓", "authenticity_token"=>"meQFus2pNrYKLDOBNFdXSR4C9Kk2zWMe/Zy3xTlD9W6kE5SeFSSmp2FxKFCW3BRc4UXmGNsJHBxT6KXKobAXPQ==", "start-date"=>"05/07/2016", "end-date"=>"05/09/2016", "total"=>"500 ", "conektaTokenId"=>"tok_Bczi9chbTL82pfXzC"}
Acceso no autorizado.

Ya se había solucionado, había podido enviar pagos sin problemas, pero de un dia para otro me aparece este error, ¿que puede ser?
Gracias.

**Comment by Janee** [comment]
Que tal @julio336 hay que revisar que tu llave pública esté en tu frontend y tu llave privada en el back. ¿Me ayudas con ésta parte?

**Comment by julio336** [comment]
Hola @Janee no he cambiado nada y mi codigo esta segun el tutorial, ¿que mas puede ser?

**Comment by Janee** [comment]
@julio336 revisando tus commits del repo que compartiste arriba, veo que estás usando Heroku, este servidor no utiliza el archivo secrets.yml de tu app, hay que configurarlas. Te dejo el link de ellos: https://devcenter.heroku.com/articles/config-vars recuerda que heroku sólo toma el ambiente *production* y no *development*

**Comment by julio336** [comment]
@Janee entiendo, pero aun no lo pruebo en producción, lo estoy probando en development y me aparece el error que te envie antes, como te digo, ya habia procesado pagos sin problemas pero de momento dejo de funcionar, ¿que puede ser?

Saludos.

**Comment by Janee** [comment]
Habrá que revisar a detalle tu código y tu cuenta, te pido envies un correo a soporte@conekta.io, con el correo con el que tienes la cuenta Conekta para darte soporte.

**Comment by MauricioMurga** [comment]
Voy a cerrar este issue por falta de actividad pero podremos re-abrirlo si hay necesidad!
