### ISSUE TITLE
Metodo de pago vacio

### ISSUE THREAD

**Issue by ghost** [conekta/conekta-ruby#30]
Hola buenas tardes, tengo mi aplicacion en ruby on rails, segui el tutorial: https://www.conekta.io/es/docs/tutorial/pagos-con-tarjeta?vertical=productos-fisicos&js-language=coffeescript

pero al momento de llegar al pago me marca este error en consola: 
![image](https://cloud.githubusercontent.com/assets/8921806/17795570/32dbaa84-657f-11e6-90dd-5b57be6375b6.png)

y en los HTTPLogs:

{
  "object": "error",
  "type": "parameter_validation_error",
  "message": "Empty payment method data.",
  "message_to_purchaser": "Método de pago vacío.",
  "param": "payment_method",
  "code": "invalid_payment_type"
}

**Comment by MauricioMurga** [comment]
Hola, una disculpa por no responder con anterioridad. ¿Sigues con este error? Voy a cerrar el issue por el momento.
