### ISSUE TITLE
NoMethodError while trying to find a charge that has a chargeback

### ISSUE THREAD

**Issue by luisguzman02** [conekta/conekta-ruby#33]
When I try to find a charge that has a chargeback it throws this error:

` Conekta::Charge.find payment.gateway_reference
NoMethodError: undefined method `load_from' for #<Chargeback:0x0055a5576c7cb0>
	from /home/deploy/chopeo/chopeo-store/shared/bundle/ruby/2.3.0/gems/activemodel-4.2.5/lib/active_model/attribute_methods.rb:433:in `method_missing'
	from /home/deploy/chopeo/chopeo-store/shared/bundle/ruby/2.3.0/gems/conekta-0.5.6/lib/conekta/util.rb:37:in `convert_to_conekta_object'
	from /home/deploy/chopeo/chopeo-store/shared/bundle/ruby/2.3.0/gems/conekta-0.5.6/lib/conekta/conekta_object.rb:81:in `load_from_enumerable'
	from /home/deploy/chopeo/chopeo-store/shared/bundle/ruby/2.3.0/gems/conekta-0.5.6/lib/conekta/conekta_object.rb:31:in `block in load_from'
	from /home/deploy/chopeo/chopeo-store/shared/bundle/ruby/2.3.0/gems/conekta-0.5.6/lib/conekta/conekta_object.rb:30:in `each'
	from /home/deploy/chopeo/chopeo-store/shared/bundle/ruby/2.3.0/gems/conekta-0.5.6/lib/conekta/conekta_object.rb:30:in `load_from'
	from /home/deploy/chopeo/chopeo-store/shared/bundle/ruby/2.3.0/gems/conekta-0.5.6/lib/conekta/operations/find.rb:8:in `find'`

Looks like it tries to create a chargeback object which doesn't exist on conekta library

**Comment by Janee** [comment]
Hola @luisguzman02 ¿nos compartes los parámetros que enviaste en el find? (id del cargo)

Saludos

**Comment by luisguzman02** [comment]
claro que si, este es el id del cargo: 577c70e201cc6a69b80017d4

**Comment by luisguzman02** [comment]
@Janee el problema esta en que mi codigo define la clase chargeback, y al hacer la conversion de los objetos de conekta busca fuera del scope de conekta, encuentra el objeto definido en mi codigo e intenta correr los mismos metodos

**Comment by luisguzman02** [comment]
@Janee una duda, porque crea una instancia de una clase fuera del scope de conekta?

**Comment by MauricioMurga** [comment]
Se arregló en este commit 393a55f913c569eb69744ac43d4333619917b2f1
