### ISSUE TITLE
undefined method `create_attr' for nil:NilClass 

### ISSUE THREAD

**Issue by betterm** [conekta/conekta-ruby#68]
Hi! I am using method create_payment_source for Conekta::Customer model in my project:
```
if customer.is_a?(Conekta::Customer) && params[:token].present?
   new_payment_source = customer.create_payment_source({ type: 'card', token_id: params[:token] })
end
```
but getting this error
```
undefined method `create_attr' for nil:NilClass 

["/home/ubuntu/apps/enviaya/shared/bundle/ruby/2.3.0/gems/conekta-2.0.0/lib/conekta/resource.rb:39:in `create_member_with_relation'", 

"/home/ubuntu/apps/enviaya/shared/bundle/ruby/2.3.0/gems/conekta-2.0.0/lib/conekta/customer.rb:57:in `create_payment_source'
```

it seems there is some problem during member(payment_source) creation. May be I should use another method to assign new payment source to existing customer? But I think I found the method in API documentation.

**Comment by eduardoconekta** [comment]
@betterm  you should try begin => rescue structure
```
begin
          source = customer.create_payment_source(source_params)
        rescue Conekta::ErrorList => error_list
          for error_detail in error_list.details do
            puts error_detail.message
          end
        end
```
what your error says is the stack trace not the api code error

**Comment by betterm** [comment]
of course, but how this rescue will help in this case???

And I already have the rescue, it doesn't helps, because we have other error, not Conekta::ErrorList

```
rescue Conekta::ErrorList => error_list
  error_list.details.each do |detail|
    Rails.logger.error {"\nConekta Card error: #{detail.param} - #{detail.message} (code: #{detail.code}, validation_error: #{detail.validation_error})"}
    @errors.add(:conekta_gateway, I18n.t(detail.code), default: detail.message)
  end
rescue Exception => e
  text = "\nERROR Shipment #{@shipment.try(:id)} \nConekta card: \n#{e.message} \n Backtrace: #{e.backtrace}\n"
  Rails.logger.error { text }
end
```

so I'm receiving the error I mentioned above, and here my thoughts: 

```
module Conekta
  class Customer < Resource
    ...
    def create_payment_source(params)
      self.create_member_with_relation('payment_sources', params, self)
    end
    ...
  end
end
```
```
module Conekta
  class Resource < ConektaObject
    ...
    def create_member_with_relation(member, params, parent)
      parent_klass = parent.class.underscored_class
      child = self.create_member(member, params)
      child.create_attr(parent_klass.to_s, parent)
      return child
    end
   ...
  end
end
```

```
module Conekta
  module Operations
    module CreateMember
      def create_member(member, params)
        _url     = [self._url, member].join('/')
        member   = member.to_sym
        response = Requestor.new.request(:post, _url, params)

        if self.send(member) &&
           (self.send(member).class.class_name == "ConektaObject" ||
            self.send(member).class.class_name == "List")
          arr = []

          if self.send(member).class.class_name == "List"
            self.send(member).add_element(response)
          else
            self.method(member).call.values.each do |_,v|
              arr << v.to_hash
            end

            arr << response
            self.send(member).load_from(arr)
            self.load_from
          end

          instances = self.send(member)
          instance = instances.last
        else
          instance = Util.types[member.to_s].new()
          instance.load_from(response)
          self.create_attr(member.to_s, instance)
          self.set_val(member.to_sym, instance)
          self.load_from
        end

        instance
      end
    end
  end
end
```



`child = self.create_member(member, params)`
the line returns nil

and here error happens
`child.create_attr(parent_klass.to_s, parent)`

So the question why it returns nil, and why it doesn't considered in the code and validation is not returned???

**Comment by eduardoconekta** [comment]
@betterm 

if create_Attr function is nil, some of  your data is not valid for 

- customer (object)
- params (type, token)

this works for me 
```
 let(:source_params) do
        {
          type:     "card",
          token_id: "tok_test_visa_4242"
        }
      end
if customer.is_a?(Conekta::Customer) && source_params[:token_id].size > 0
          new_payment_source = customer.create_payment_source({ type: 'card', token_id: source_params[:token_id] })
        end
```
do you have some similar ?
Also you can check the customer_spec to see how to create a payment_source
`conekta-ruby/spec/conekta/2.0.0/customer_spec.rb `

**Comment by betterm** [comment]
Of course this works in 99% cases, but sometimes it returns the error, but if there some wrong data there probably should be validation error/message for this, shouldn't  it?

**Comment by eduardoconekta** [comment]
Yes @betterm you are right, we internally have validations in the api for every model to check that the request body  matches with this structure works 99% of the time, may be you are sending some data we haven't mapped yet.
Please make a gist with your entire customer data we will try to reproduce the problem with your code, only customer data, without sensitive data.

**Comment by eduardoconekta** [comment]
Hi @betterm  can you try our new version please ? it is a Exception refactored version 
https://github.com/conekta/conekta-ruby/tree/master

**Comment by nicklloyd** [comment]
Hi @eduardoconekta, we've been experiencing same issue so I'm following along. 

Checkout the new version. Looks like a step in the right direction! Unfortunately, we're seeing an issue with the new `Conekta::Error` initialisation/handling. 

```
  71) Conekta::TaxLine updating tax lines unsuccessful tax line update
      Failure/Error:
        expect {
          tax_line.update(amount: -1)
        }.to raise_error(Conekta::Error)

        expected Conekta::Error, got #<NoMethodError: undefined method `[]=' for nil:NilClass> with backtrace:
          # ./lib/conekta/conekta_object.rb:10:in `set_val'
          # ./lib/conekta/conekta_object.rb:104:in `load_from_enumerable'
          # ./lib/conekta/conekta_object.rb:35:in `block in load_from'
          # ./lib/conekta/conekta_object.rb:34:in `each'
          # ./lib/conekta/conekta_object.rb:34:in `load_from'
          # ./lib/conekta/error_details.rb:6:in `initialize'
          # ./lib/conekta/error.rb:10:in `new'
          # ./lib/conekta/error.rb:10:in `block in initialize'
          # ./lib/conekta/error.rb:9:in `collect'
          # ./lib/conekta/error.rb:9:in `initialize'
          # ./lib/conekta/error.rb:32:in `new'
          # ./lib/conekta/error.rb:32:in `error_handler'
          # ./lib/conekta/requestor.rb:30:in `rescue in request'
          # ./lib/conekta/requestor.rb:24:in `request'
          # ./lib/conekta/operations/create.rb:7:in `create'
          # ./spec/conekta/2.0.0/tax_line_spec.rb:20:in `block (2 levels) in <top (required)>'
          # ./spec/conekta/2.0.0/tax_line_spec.rb:21:in `block (2 levels) in <top (required)>'
          # ./spec/conekta/2.0.0/tax_line_spec.rb:40:in `block (4 levels) in <top (required)>'
          # ./spec/conekta/2.0.0/tax_line_spec.rb:39:in `block (3 levels) in <top (required)>'
      # ./spec/conekta/2.0.0/tax_line_spec.rb:39:in `block (3 levels) in <top (required)>'

Finished in 1 minute 27.11 seconds (files took 0.32986 seconds to load)
99 examples, 71 failures
```

**Comment by eduardoconekta** [comment]
@betterm I try to reproduce with a fresh clone of the repo but i can't  find the issue, conekta_object its instancing the object already, there wasn't any fails until object creation

you are running he specs in this way  ?
![captura de pantalla 2017-10-06 a la s 11 04 41](https://user-images.githubusercontent.com/26972091/31287226-2f4727e8-aa86-11e7-8985-a249f7efedaa.png)

**Comment by nicklloyd** [comment]
I’m afraid I’m away from keyboard for the next couple days. This was indeed how I was running the spec.

I do recall one failure seemingly trying to reach another service on localhost:

yea, not sure what's up with that... one of their specs actually fails with 

```      # Errno::ECONNREFUSED:
      #   Connection refused - connect(2) for "localhost" port 3001
      #   ./lib/conekta/requestor.rb:26:in `call'

```

**Comment by nicklloyd** [comment]
![screen shot 2017-10-09 at 10 15 33](https://user-images.githubusercontent.com/1973952/31329571-12652d4e-acdb-11e7-8b76-72bf3e983ac1.png)

**Comment by betterm** [comment]
we also have the new error, we got it after update to newest version

**Comment by nicklloyd** [comment]
@betterm we've discovered the issue is related to users who've added 6 or more payment sources. 

I've submitted a PR for the new release that prevents the error: https://github.com/conekta/conekta-ruby/pull/78

That said, be aware that the API only returns 5 payment sources. In the raw response there is a `has_more` attribute and a link to the `next_page_url`, but the gem does not seem make use of it...

**Comment by eduardoconekta** [comment]
@nicklloyd thanks a lot for your contribution is already on master 🎉  🌮
