### ISSUE TITLE
Basic Auth Encoding issue

### ISSUE THREAD

**Issue by nicklloyd** [conekta/conekta-ruby#71]
https://github.com/conekta/conekta-ruby/blob/07976948984abc6a062a2d9202dc1cc17b6e8615/lib/conekta/requestor.rb#L63

This is causing issue with the basic auth.

Better to remove and use Faraday itself to handle auth and avoid the single quotes?

```faraday.basic_auth(self.api_key, '')```

**Comment by eduardoconekta** [comment]
Why is this causing an issue ? 
Whats the error returned ? 
Can you please explain your flow of code to reproduce the error ? @nicklloyd thanks

**Comment by nicklloyd** [comment]
This is me simply following the example from your docs: https://developers.conekta.com/tutorials/card

The tests were failing on me as well...

**Comment by eduardoconekta** [comment]
ok, i have runned the tests as well and in my case all pass 
![captura de pantalla 2017-09-05 a la s 11 08 54](https://user-images.githubusercontent.com/26972091/30070947-a63cf482-922a-11e7-8680-f88674edeb21.png)
please can you check that all the dependencies are installed please ? 
or re run your test and show me the output

**Comment by nicklloyd** [comment]
All dependencies are installed. 
```
    # @param [Payment] payment
    # @param [String] email
    # @param [String] token_id

    # @return [Conekta::Customer]
    def create_customer(payment, email, token_id)      
      Conekta::Customer.create({
        name: account_holder_name,
        email: email,
        payment_sources: [{
          type: 'card',
          token_id: token_id
        }]
      })
    rescue Conekta::ErrorList => error_list
      error_list
    end
```

results in the same response as vcr cassette above and: 

```
 Failure/Error:
       Conekta::Customer.create({
         name: account_holder_name,
         email: ticket.user.email,
         payment_sources: [{
           type: 'card',
           token_id: token_id
         }]
       })

     Oj::ParseError:
       unexpected character at line 1, column 1 [parse.c:661]
```

**Comment by eduardoconekta** [comment]
Is there any utf-8 character like ñ or accent or tilde un any of your fields ?

**Comment by nicklloyd** [comment]
nope: see above:
```
'{"name":"Rick Floyd","email":"test.detailed_with_tickets@playpass.be","payment_sources":[{"type":"card","token_id":"tok_test_visa_4242"}]}'
```

That parse error is because the api is returning an html response...

**Comment by eduardoconekta** [comment]
ok, i think is not the api 
![captura de pantalla 2017-09-05 a la s 13 19 59](https://user-images.githubusercontent.com/26972091/30075931-f764bb6c-923c-11e7-8417-76558082e965.png)

let me do some test's with the specific code you have, can you make a gist with your code to check it please?

**Comment by nicklloyd** [comment]
I'll have a look tomorrow as I actually have a feeling this is a Faraday adapter issue. 

That said, any reason to _not_ use `faraday.basic_auth(self.api_key, '')` ?
 
http://www.rubydoc.info/github/lostisland/faraday/Faraday%2FConnection%3Abasic_auth

**Comment by nicklloyd** [comment]
Can't say I've got too much time to dig into why, but switching to the default_adapter for Faraday while previously set to Excon (supported by Faraday), leads to improper encoding of the Authorization header.

That said, `encode64` adds a newline `\n` which is causing the auth to fail. ([see header](https://github.com/conekta/conekta-ruby/issues/71#issuecomment-327214990))

```
"Basic #{ Base64.encode64("#{api_key}" + ':')}" 
=> "Basic a2V5X3h3aHZqRllzWXROYUFmRVljcWtlOHc6\n"
```
This can be avoided by using `strict_encode64` instead. 
```
"Basic #{ Base64.strict_encode64("#{api_key}" + ':')}"
=> "Basic a2V5X3h3aHZqRllzWXROYUFmRVljcTMyMTQ6"
```

Let me know if this fix is something you are comfortable with implementing.

**Comment by Janee** [comment]
@eduardoconekta can you help us with this?

**Comment by eduardoconekta** [comment]
@nicklloyd ok thanks we will do the change for strict_encode64 sounds good 👍

**Comment by eduardoconekta** [comment]
https://github.com/conekta/conekta-ruby/pull/75 merged change @nicklloyd  thanks 👍  can you please close the issue ?

**Comment by nicklloyd** [comment]
Thanks!
