### ISSUE TITLE
Error: The route requested does not exist on conekta hello-conekta-ruby-subscription

### ISSUE THREAD

**Issue by carlosgomez2** [conekta/conekta-ruby#88]
Hola, estoy recibiendo el mensaje `Conekta::ResourceNotFoundError in CustomersController#update` al utilizar el ejemplo de [hello-conekta-ruby-subscription](https://github.com/conekta-examples/hello-conekta-ruby-subscription) en el controlador Customers en la linea 30 `customer.create_card(token: params["conektaTokenId"])`, al agregar la tarjeta del customer con el Número de tarjeta: 5555555555554444, CVC 1234, Expiración 09/2022, dando en el botóm agregar tarjeta.

Me pueden ayudar a entender por que recibo ese mensaje?

Saludos!

**Comment by mauroarcet** [comment]
Hola @carlosgomez2, 

¿Podrías abrir el issue en ese proyecto?
