### ISSUE TITLE
uninitialized constant Conekta::ErrorList

### ISSUE THREAD

**Issue by eadbhard** [conekta/conekta-ruby#89]
Hi there,

When calling Conekta::Order.create() from a controller, if there is an error in the call, the rescue part crashes and throws in the following error:

uninitialized constant Conekta::ErrorList

Please help, thanks.

**Comment by omarsve** [comment]
Hi i have the same problem, I tried Error only and it worked but then i get 

uninitialized constant Conekta::Order

I don't know what could be the problem.

**Comment by eduardoconekta** [comment]
@eadbhard @omarsve thanks to reporting this error can you share os a gist with your code to try to reproduce ? or are you able to capture a log of that error ?,

**Comment by Scoup** [comment]
This bug's still alive.
```ruby
    begin
      self.response = Conekta::Order.create(order_data)
    rescue Conekta::ErrorList => list # <=== this will throw error
      # need to use "Exception" directly
    end
```

**Comment by leofischer** [comment]
This doesn't seem to be a bug with the library but rather the documentation and references an older implementation which was inconsistent with standard Ruby usage.  I will create a PR to have this pushed in the next few days.  The correct usage should be

```ruby
    begin
      self.response = Conekta::Order.create(order_data)
    rescue Conekta::ErrorList => list # <=== this will throw error
      # need to use "Exception" directly
    end
```

**Comment by leofischer** [comment]
PR https://github.com/conekta/docs/pull/437 is now pending code review and will fix this issue.

**Comment by leofischer** [comment]
@eadbhard, @Scoup - the documentation has now been corrected to address this issue
