### ISSUE TITLE
Empty `shipping_lines` raises exception

### ISSUE THREAD

**Issue by joseramonc** [conekta/conekta-ruby#90]
Docs say that order's `shipping_lines` are optional here: 
<img width="355" alt="image" src="https://user-images.githubusercontent.com/1993929/40077905-9f8ca3a0-5848-11e8-9b26-792d86e6689f.png">
but, when I try to create an order without `shipping_lines` lib raises an exception:

<img width="649" alt="image" src="https://user-images.githubusercontent.com/1993929/40077936-b9cc547c-5848-11e8-80b8-39c49ae77b31.png">

Is there something I'm missing?

**Comment by eduardoconekta** [comment]
@mauroarcet
