### ISSUE TITLE
How to use Conekta in tests?

### ISSUE THREAD

**Issue by CCLJ** [conekta/conekta-ruby#95]
I'm not sure if this is the right place, but I can't seem to find any information on how to use the Conekta API inside the integration tests. Hoped someone can direct me in the right direction.

**Comment by Scoup** [comment]
You can use the attribute `livemode` false.
here a sample using ruby:
```ruby
  def order_data
    {
      livemode: Rails.env.production?, # true => production, false = sandbox
      currency: currency,
      customer_info: {
        customer_id: user.conekta_customer_id
      },
      line_items: conekta_items_data,
      discount_lines: conekta_discounts_data,
      charges: [{
        payment_method: {
          payment_source_id: conekta_payment_method.remote_id,
          type: external_remote_type,
          expires_at: expires_on
        }
      }]
    }
  end
```

**Comment by eduenriquez** [comment]
@CCLJ was @Scoup answer good for you?, can we close this issue ?

**Comment by CCLJ** [comment]
@Scoup thanks for the answerm I'll try it out. @eduenriquez I haven't have time to try this, but we can close the issue for now and reopen it if this doesn't work when I try it.

**Comment by eduenriquez** [comment]
ok @CCLJ sounds good to me and yes feel free to reopen this issue or if you prefer ask via support@conekta.com

**Comment by CCLJ** [comment]
@eduenriquez will do if I need, thanks:)
